/**
 * Hand-formatted YAML writing utilities.
 *
 * We hand-write YAML rather than using a library to preserve the existing
 * commission log's comments, spacing, and formatting. The commission log
 * is a standing research instrument with a carefully maintained header;
 * library serialization would strip all of that.
 */

import fs from 'node:fs';
import path from 'node:path';

// ── Commission log ───────────────────────────────────────────────────

/**
 * Append a skeleton commission log entry for a newly created writ.
 * Human-judgment fields are written as null for the patron to fill in.
 */
export function appendCommissionLogEntry(
  logPath: string,
  writ: { id: string; title: string; codex?: string },
): void {
  // Escape the title for YAML (wrap in double quotes, escape internal quotes)
  const safeTitle = writ.title.replace(/"/g, '\\"');
  const codexLine = writ.codex ? `    codex: ${writ.codex}` : '    codex: null';

  const entry = `
  - id: ${writ.id}
    title: "${safeTitle}"
${codexLine}
    complexity: null
    spec_quality_pre: null
    outcome: null
    revision_required: null
    spec_quality_post: null
    failure_mode: null
`;

  fs.appendFileSync(logPath, entry, 'utf-8');
}

// ── Commission artifacts ─────────────────────────────────────────────

/**
 * Write commission.md — the writ body as a permanent record.
 * This is the spec/prompt that was dispatched to the anima.
 */
export function writeCommissionMd(
  commissionsDir: string,
  writ: { id: string; title: string; body: string },
): void {
  const filePath = path.join(commissionsDir, writ.id, 'commission.md');
  // Don't overwrite — the patron may have edited the file
  if (fs.existsSync(filePath)) return;
  fs.writeFileSync(filePath, writ.body, 'utf-8');
}

/**
 * Write a review.md template — placeholder for patron review.
 */
export function writeReviewTemplate(
  commissionsDir: string,
  writ: { id: string; title: string },
): void {
  const filePath = path.join(commissionsDir, writ.id, 'review.md');
  // Don't overwrite — the patron may have started writing
  if (fs.existsSync(filePath)) return;

  const template = `# Review: ${writ.id}

## ${writ.title}

**Outcome:**
<!-- success | partial | wrong | abandoned -->

**Spec quality (post-review):**
<!-- strong | adequate | weak -->

**Revision required:**
<!-- yes | no -->

**Failure mode (if not success):**
<!-- spec_ambiguous | requirement_wrong | execution_error | complexity_overrun -->

## Notes

<!-- What went well? What went wrong? What would you change about the spec? -->
`;

  fs.writeFileSync(filePath, template, 'utf-8');
}

// ── Session YAML ─────────────────────────────────────────────────────

/**
 * Write a session record YAML file in the commission's sessions/ directory.
 */
export function writeSessionRecord(
  commissionsDir: string,
  writId: string,
  session: {
    id: string;
    startedAt: string;
    endedAt?: string;
    durationMs?: number;
    status: string;
    provider: string;
    exitCode?: number;
    error?: string;
    costUsd?: number;
    tokenUsage?: {
      inputTokens: number;
      outputTokens: number;
      cacheReadTokens?: number;
      cacheWriteTokens?: number;
    };
  },
): void {
  const dir = path.join(commissionsDir, writId, 'sessions');
  fs.mkdirSync(dir, { recursive: true });

  const lines: string[] = [
    `# Session: ${session.id}`,
    `# Auto-generated by The Laboratory`,
    '',
    `id: ${session.id}`,
    `writ_id: ${writId}`,
    `status: ${session.status}`,
    `provider: ${session.provider}`,
    `started_at: ${session.startedAt}`,
  ];

  if (session.endedAt) lines.push(`ended_at: ${session.endedAt}`);
  if (session.durationMs !== undefined) lines.push(`duration_ms: ${session.durationMs}`);
  if (session.exitCode !== undefined) lines.push(`exit_code: ${session.exitCode}`);
  if (session.error) lines.push(`error: "${session.error.replace(/"/g, '\\"')}"`);
  if (session.costUsd !== undefined) lines.push(`cost_usd: ${session.costUsd}`);

  if (session.tokenUsage) {
    lines.push('token_usage:');
    lines.push(`  input_tokens: ${session.tokenUsage.inputTokens}`);
    lines.push(`  output_tokens: ${session.tokenUsage.outputTokens}`);
    if (session.tokenUsage.cacheReadTokens !== undefined) {
      lines.push(`  cache_read_tokens: ${session.tokenUsage.cacheReadTokens}`);
    }
    if (session.tokenUsage.cacheWriteTokens !== undefined) {
      lines.push(`  cache_write_tokens: ${session.tokenUsage.cacheWriteTokens}`);
    }
  }

  lines.push(''); // trailing newline
  fs.writeFileSync(path.join(dir, `${session.id}.yaml`), lines.join('\n'), 'utf-8');
}
